// GENERATED BY tools/gig02/hit_area.py. DO NOT EDIT.
//
// The hit area's corners: the convex hull of the 23 corners walked in
// play on 2026-09-06, the stairs, the trash pile and the sniper's
// walkway, pushed out by 12 m. The top step is outside on purpose,
// because it is where V arrives and where the way-out marker sits.
//
// THE SAME CORNERS are the outline of the trigger area node the way-out
// pins point at (gen_community.hit_area_node), so the shape the minimap
// draws is the shape that ends the leg. They were a hand-copied copy
// until 2026-09-06; regenerate rather than edit.
module CyberpunkCodes.Gig02

public class CCGig02Area {
    public static func X() -> array<Float> {
        let a: array<Float>;
        ArrayPush(a, -421.028);
        ArrayPush(a, -384.860);
        ArrayPush(a, -361.474);
        ArrayPush(a, -355.678);
        ArrayPush(a, -356.318);
        ArrayPush(a, -383.153);
        ArrayPush(a, -397.460);
        ArrayPush(a, -412.399);
        return a;
    }

    public static func Y() -> array<Float> {
        let a: array<Float>;
        ArrayPush(a, 1284.475);
        ArrayPush(a, 1187.719);
        ArrayPush(a, 1200.500);
        ArrayPush(a, 1214.097);
        ArrayPush(a, 1245.280);
        ArrayPush(a, 1314.169);
        ArrayPush(a, 1314.663);
        ArrayPush(a, 1309.554);
        return a;
    }
}
